// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type AIModel struct {

	// AI Provider: AI service provider or organization name. For example: <code>OpenAI</code>, <code>Anthropic</code>, <code>Google</code>, or <code>Internal</code>.
	AiProvider string `json:"ai_provider" parquet:"ai_provider"`

	// Name: Human-readable model name. For example: <code>gpt-4o</code>, <code>claude-3-sonnet</code>, or <code>text-embedding-ada-002</code>.
	Name string `json:"name" parquet:"name"`

	// Unique ID: The unique identifier of the AI model.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Version: Model version identifier. For example: <code>2024-05-13</code>, <code>v2.1.0</code>, or <code>beta</code>.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *AIModel) Observable() (*int, string) {
	return nil, ""
}

var AIModelFields = []arrow.Field{
	{Name: "ai_provider", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var AIModelStruct = arrow.StructOf(AIModelFields...)

var AIModelSchema = arrow.NewSchema(AIModelFields, nil)
var AIModelClassname = "ai_model"
