// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type API struct {

	// Group: The information pertaining to the API group.
	Group *Group `json:"group,omitempty" parquet:"group,optional"`

	// Operation: Verb/Operation associated with the request
	Operation string `json:"operation" parquet:"operation"`

	// API Request Details: Details pertaining to the API request.
	Request *RequestElements `json:"request,omitempty" parquet:"request,optional"`

	// API Response Details: Details pertaining to the API response.
	Response *ResponseElements `json:"response,omitempty" parquet:"response,optional"`

	// Service: The information pertaining to the API service.
	Service *Service `json:"service,omitempty" parquet:"service,optional"`

	// Token: The API or client token used to authenticate or authorize the API request. This attribute contains the base <code>token</code> object that represents: (1) IdP-issued client tokens (type_id: 6) such as Okta API tokens or Microsoft Entra ID Application Registration client secrets, or (2) generic API tokens/keys (type_id: 7) used for SaaS application authentication. Use this attribute when the API request was authenticated using a token that should be tracked as part of the API activity event. Note: Protocol-specific authentication tokens (Kerberos, OIDC, SAML) should be represented using <code>authentication_token</code> in authentication events, not in API activity events.
	Token *Token `json:"token,omitempty" parquet:"token,optional"`

	// Version: The version of the API service.
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}

func (v *API) Observable() (*int, string) {
	return nil, ""
}

var APIFields = []arrow.Field{
	{Name: "group", Type: GroupStruct, Nullable: true},
	{Name: "operation", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "request", Type: RequestElementsStruct, Nullable: true},
	{Name: "response", Type: ResponseElementsStruct, Nullable: true},
	{Name: "service", Type: ServiceStruct, Nullable: true},
	{Name: "token", Type: TokenStruct, Nullable: true},
	{Name: "version", Type: arrow.BinaryTypes.String, Nullable: true},
}

var APIStruct = arrow.StructOf(APIFields...)

var APISchema = arrow.NewSchema(APIFields, nil)
var APIClassname = "api"
