// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type AuthenticationToken struct {

	// Created Time: The time that the authentication token was created or issued. This corresponds to the token issuance time, such as the <code>iat</code> (issued at) claim in OIDC tokens, the issue instant in SAML assertions, or the ticket start time in Kerberos tickets.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// Encryption Details: The encryption details of the authentication token.
	EncryptionDetails *EncryptionDetails `json:"encryption_details,omitempty" parquet:"encryption_details,optional"`

	// Expiration Time: The expiration time of the authentication token.
	ExpirationTime int64 `json:"expiration_time,omitempty" parquet:"expiration_time,timestamp_millis,timestamp(millisecond),optional"`

	// Renewable: Indicates whether the authentication token is renewable.
	IsRenewable *bool `json:"is_renewable,omitempty" parquet:"is_renewable,optional"`

	// Kerberos Flags: A bitmask, either in hexadecimal or decimal form, which encodes various attributes or permissions associated with a Kerberos ticket. These flags delineate specific characteristics of the ticket, such as its renewability or forwardability.
	KerberosFlags *string `json:"kerberos_flags,omitempty" parquet:"kerberos_flags,optional"`

	// Modified Time: The last time the token was updated.
	ModifiedTime int64 `json:"modified_time,omitempty" parquet:"modified_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The human-friendly name of a token or key, if available, such as the <code>name</code> from the Okta API Token API.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Tenant UID: The unique identifier of the tenant or organization that owns the token or key, or the tenant context in which the token is authorized for use. This is particularly relevant in multi-tenant Identity Provider scenarios where tokens are scoped to specific tenants.
	TenantUid *string `json:"tenant_uid,omitempty" parquet:"tenant_uid,optional"`

	// Type: The type of the authentication token.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The normalized authentication token type identifier. This attribute restricts the base <code>token.type_id</code> enum to only protocol-specific authentication token types (values 0, 1-5, 99). API tokens and client tokens (values 6-7) are not valid for <code>authentication_token</code> - use the base <code>token</code> object for those types.
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`

	// Unique ID: The unique ID of a token or key, if available, such as the <code>Secret ID</code> of Entra ID Application Registration Client Secrets.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Network Zone: The network zone or geographic region that the token or key is authorized to be used from. This may represent network-based access restrictions, geographic limitations, or other zone-based authorization policies. Examples include Okta's network zone restrictions or cloud provider region restrictions.
	Zone *string `json:"zone,omitempty" parquet:"zone,optional"`
}

func (v *AuthenticationToken) Observable() (*int, string) {
	return nil, ""
}

var AuthenticationTokenFields = []arrow.Field{
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "encryption_details", Type: EncryptionDetailsStruct, Nullable: true},
	{Name: "expiration_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "is_renewable", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "kerberos_flags", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "modified_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "tenant_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "zone", Type: arrow.BinaryTypes.String, Nullable: true},
}

var AuthenticationTokenStruct = arrow.StructOf(AuthenticationTokenFields...)

var AuthenticationTokenSchema = arrow.NewSchema(AuthenticationTokenFields, nil)
var AuthenticationTokenClassname = "authentication_token"
