// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type GPUInformation struct {

	// Bus Type: The attachment bus or interface standard, normalized to the caption of the bus_type_id value. In the case of 'Other', it is defined by the event source.
	BusType *string `json:"bus_type,omitempty" parquet:"bus_type,optional"`

	// Bus Type ID: The normalized identifier of the attachment bus or interface standard.
	BusTypeId *int32 `json:"bus_type_id,omitempty" parquet:"bus_type_id,optional"`

	// Cores: The number of processing cores or compute units for the component.
	Cores *int32 `json:"cores,omitempty" parquet:"cores,optional"`

	// Model: The model name of the GPU. For example: <code>GeForce RTX A6000</code>, <code>Radeon PRO W7900</code>, or <code>Intel Data Center GPU Max 1550</code>.
	Model *string `json:"model,omitempty" parquet:"model,optional"`

	// Vendor Name: The name of the vendor of the GPU. For example: <code>NVIDIA</code>, <code>AMD</code>, or <code>Intel</code>.
	VendorName *string `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`

	// VRAM Mode: The video memory attachment mode, indicating how the VRAM hardware is integrated with the system (e.g., shared or dedicated), normalized to the caption of the vram_mode_id value. For 'Other', the exact attachment mode is defined by the event source.
	VramMode *string `json:"vram_mode,omitempty" parquet:"vram_mode,optional"`

	// VRAM Mode ID: The normalized identifier of the video memory attachment mode.
	VramModeId *int32 `json:"vram_mode_id,omitempty" parquet:"vram_mode_id,optional"`

	// VRAM Size: The total amount of installed video RAM.
	VramSize *int32 `json:"vram_size,omitempty" parquet:"vram_size,optional"`
}

func (v *GPUInformation) Observable() (*int, string) {
	return nil, ""
}

var GPUInformationFields = []arrow.Field{
	{Name: "bus_type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "bus_type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "cores", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "model", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "vendor_name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "vram_mode", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "vram_mode_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "vram_size", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var GPUInformationStruct = arrow.StructOf(GPUInformationFields...)

var GPUInformationSchema = arrow.NewSchema(GPUInformationFields, nil)
var GPUInformationClassname = "gpu_info"
