// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type MessageContext struct {

	// AI Role: The normalized caption of the <code>ai_role_id</code>.
	AiRole *string `json:"ai_role,omitempty" parquet:"ai_role,optional"`

	// AI Role ID: Specifies the functional role of the AI within the context of this message, such as retrieving information, assisting reasoning, executing a tool, or generating content.
	AiRoleId *int32 `json:"ai_role_id,omitempty" parquet:"ai_role_id,optional"`

	// Application: The initiating client application. In AI systems, this represents the client-side application or framework that initiates requests (e.g., LangChain application, web browser, mobile app, SDK implementation).
	Application *Application `json:"application,omitempty" parquet:"application,optional"`

	// Completion Tokens: Number of tokens in the model's response/completion for this message.
	CompletionTokens *int32 `json:"completion_tokens,omitempty" parquet:"completion_tokens,optional"`

	// Name: The name or identifier of the message context. In AI systems, this could be the conversation ID, session name, thread identifier, or interaction name (e.g., 'user-session-123', 'conversation-abc', 'chat-thread-456').
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Prompt Tokens: Number of tokens in the input prompt for this message.
	PromptTokens *int32 `json:"prompt_tokens,omitempty" parquet:"prompt_tokens,optional"`

	// Service: The server or service handling the request. In AI systems, this represents the AI service, API endpoint, or agent that processes and responds to requests (e.g., OpenAI API service, Claude API service, internal AI model service).
	Service *Service `json:"service,omitempty" parquet:"service,optional"`

	// Total Tokens: Total number of tokens used for this message (prompt + completion).
	TotalTokens *int32 `json:"total_tokens,omitempty" parquet:"total_tokens,optional"`

	// Unique ID: The unique identifier of the message context. This could be a session ID, conversation ID, or other unique identifier that allows correlation of messages within the same context.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

func (v *MessageContext) Observable() (*int, string) {
	return nil, ""
}

var MessageContextFields = []arrow.Field{
	{Name: "ai_role", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "ai_role_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "application", Type: ApplicationStruct, Nullable: true},
	{Name: "completion_tokens", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "prompt_tokens", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "service", Type: ServiceStruct, Nullable: true},
	{Name: "total_tokens", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var MessageContextStruct = arrow.StructOf(MessageContextFields...)

var MessageContextSchema = arrow.NewSchema(MessageContextFields, nil)
var MessageContextClassname = "message_context"
