// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Packet struct {

	// Encoding: The human-readable name of the encoding used to represent the packet data in the <code>value</code> field. This should match the caption associated with <code>encoding_id</code>. If <code>encoding_id</code> is 99 (Other), this field contains the original data source–specific encoding value.
	Encoding *string `json:"encoding,omitempty" parquet:"encoding,optional"`

	// Encoding ID: The normalized identifier of the encoding method used to represent the packet data as a string.
	EncodingId *int32 `json:"encoding_id,omitempty" parquet:"encoding_id,optional"`

	// End Offset: The ending byte position of this packet within a capture file or stream.
	EndOffset *int64 `json:"end_offset,omitempty" parquet:"end_offset,optional"`

	// Format: The human-readable name of the packet capture file format in which the packet is stored. This should match the caption associated with <code>format_id</code>. If <code>format_id</code> is 99 (Other), this field contains the original data source–specific format value.
	Format *string `json:"format,omitempty" parquet:"format,optional"`

	// Format ID: The normalized identifier of the packet capture format.
	FormatId *int32 `json:"format_id,omitempty" parquet:"format_id,optional"`

	// Sequence Number: The relative order number of this packet within its capture context (such as a PCAP file, network session, or reconstructed stream). This represents chronological capture order, distinct from both protocol-level sequencing (such as TCP sequence numbers).
	SequenceNumber *int64 `json:"sequence_number,omitempty" parquet:"sequence_number,optional"`

	// Source: The human-readable name describing how or where the packet was obtained. This should match the caption associated with <code>source_id</code>. If <code>source_id</code> is 99 (Other), this field contains the original data source–specific value.
	Source *string `json:"source,omitempty" parquet:"source,optional"`

	// Source ID: A normalized numeric identifier that specifies how the packet was obtained or generated.
	SourceId *int32 `json:"source_id,omitempty" parquet:"source_id,optional"`

	// Start Offset: The starting byte position of this packet within a capture file or stream.
	StartOffset *int64 `json:"start_offset,omitempty" parquet:"start_offset,optional"`

	// Value: The actual packet data, represented as a string. The format of this string is determined by the specified <code>encoding_id</code> (e.g., Base64, Hexadecimal, or URL Encoded).
	Value string `json:"value" parquet:"value"`
}

func (v *Packet) Observable() (*int, string) {
	return nil, ""
}

var PacketFields = []arrow.Field{
	{Name: "encoding", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "encoding_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "end_offset", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "format", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "format_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "sequence_number", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "source", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "source_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "start_offset", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "value", Type: arrow.BinaryTypes.String, Nullable: false},
}

var PacketStruct = arrow.StructOf(PacketFields...)

var PacketSchema = arrow.NewSchema(PacketFields, nil)
var PacketClassname = "packet"
