// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type PrivilegeAttackInfo struct {

	// MITRE ATT&CK® Details: The MITRE ATT&CK technique that these privileges could enable.
	Attack MITREATTCKATLAS `json:"attack" parquet:"attack"`

	// Privilege Info List: The list of privilege information objects, where each element describes a specific privilege that could enable the associated attack technique.
	PrivilegeInfoList []PrivilegeInfo `json:"privilege_info_list" parquet:"privilege_info_list,list"`
}

func (v *PrivilegeAttackInfo) Observable() (*int, string) {
	return nil, ""
}

var PrivilegeAttackInfoFields = []arrow.Field{
	{Name: "attack", Type: MITREATTCKATLASStruct, Nullable: false},
	{Name: "privilege_info_list", Type: arrow.ListOf(PrivilegeInfoStruct), Nullable: false},
}

var PrivilegeAttackInfoStruct = arrow.StructOf(PrivilegeAttackInfoFields...)

var PrivilegeAttackInfoSchema = arrow.NewSchema(PrivilegeAttackInfoFields, nil)
var PrivilegeAttackInfoClassname = "privilege_attack_info"
