// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type PrivilegeInfo struct {

	// Is Unused: Indicates whether the privilege is unused within the analysis timeframe.
	IsUnused *bool `json:"is_unused,omitempty" parquet:"is_unused,optional"`

	// Last Used Time: The most recent time this privilege was used.
	LastUsedTime int64 `json:"last_used_time,omitempty" parquet:"last_used_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The name of the privilege, action, or permission. Examples: <code>GetObject</code>, <code>CreateStoreImageTask</code> (AWS); <code>Microsoft.Storage/storageAccounts/read</code> (Azure); <code>storage.objects.get</code> (GCP).
	Name string `json:"name" parquet:"name"`

	// Type: The type or category of the privilege, normalized to the caption of the <code>type_id</code> value. In the case of 'Other', it is defined by the event source.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The normalized type of the privilege.
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`
}

func (v *PrivilegeInfo) Observable() (*int, string) {
	return nil, ""
}

var PrivilegeInfoFields = []arrow.Field{
	{Name: "is_unused", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "last_used_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var PrivilegeInfoStruct = arrow.StructOf(PrivilegeInfoFields...)

var PrivilegeInfoSchema = arrow.NewSchema(PrivilegeInfoFields, nil)
var PrivilegeInfoClassname = "privilege_info"
