// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type ServicePrivilegeAnalysis struct {

	// All Privileges Unused: Indicates whether all privileges within this service are unused.
	AllPrivilegesUnused *bool `json:"all_privileges_unused,omitempty" parquet:"all_privileges_unused,optional"`

	// Analyzed Privileges Count: The total count of privileges analyzed within this service.
	AnalyzedPrivilegesCount *int32 `json:"analyzed_privileges_count,omitempty" parquet:"analyzed_privileges_count,optional"`

	// Execute Privilege Count: The count of execute-type privileges within this service.
	ExecuteCount *int32 `json:"execute_count,omitempty" parquet:"execute_count,optional"`

	// Last Used Time: The most recent time any privilege in this service was used.
	LastUsedTime int64 `json:"last_used_time,omitempty" parquet:"last_used_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The service or namespace identifier. Examples: <code>s3</code>, <code>ec2</code> (AWS); <code>Microsoft.Storage</code> (Azure); <code>storage</code> (GCP).
	Name string `json:"name" parquet:"name"`

	// Privilege Attack Info List: The list of privilege-to-attack mappings for this service.
	PrivilegeAttackInfoList []PrivilegeAttackInfo `json:"privilege_attack_info_list,omitempty" parquet:"privilege_attack_info_list,list,optional"`

	// Read Privilege Count: The count of read-type privileges within this service.
	ReadCount *int32 `json:"read_count,omitempty" parquet:"read_count,optional"`

	// Unused Privileges Count: The count of unused privileges within this service.
	UnusedPrivilegesCount *int32 `json:"unused_privileges_count,omitempty" parquet:"unused_privileges_count,optional"`

	// Write Privilege Count: The count of write-type privileges within this service.
	WriteCount *int32 `json:"write_count,omitempty" parquet:"write_count,optional"`
}

func (v *ServicePrivilegeAnalysis) Observable() (*int, string) {
	return nil, ""
}

var ServicePrivilegeAnalysisFields = []arrow.Field{
	{Name: "all_privileges_unused", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "analyzed_privileges_count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "execute_count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "last_used_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "privilege_attack_info_list", Type: arrow.ListOf(PrivilegeAttackInfoStruct), Nullable: true},
	{Name: "read_count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "unused_privileges_count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "write_count", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
}

var ServicePrivilegeAnalysisStruct = arrow.StructOf(ServicePrivilegeAnalysisFields...)

var ServicePrivilegeAnalysisSchema = arrow.NewSchema(ServicePrivilegeAnalysisFields, nil)
var ServicePrivilegeAnalysisClassname = "service_privilege_analysis"
