// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_8_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Token struct {

	// Created Time: The time that the token was created.
	CreatedTime int64 `json:"created_time,omitempty" parquet:"created_time,timestamp_millis,timestamp(millisecond),optional"`

	// Expiration Time: The expiration time of the token.
	ExpirationTime int64 `json:"expiration_time,omitempty" parquet:"expiration_time,timestamp_millis,timestamp(millisecond),optional"`

	// Renewable: Indicates whether the token is renewable.
	IsRenewable *bool `json:"is_renewable,omitempty" parquet:"is_renewable,optional"`

	// Modified Time: The last time the token was updated.
	ModifiedTime int64 `json:"modified_time,omitempty" parquet:"modified_time,timestamp_millis,timestamp(millisecond),optional"`

	// Name: The human-friendly name of a token or key, if available, such as the <code>name</code> from the Okta API Token API.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Tenant UID: The unique identifier of the tenant or organization that owns the token or key, or the tenant context in which the token is authorized for use. This is particularly relevant in multi-tenant Identity Provider scenarios where tokens are scoped to specific tenants.
	TenantUid *string `json:"tenant_uid,omitempty" parquet:"tenant_uid,optional"`

	// Type: The type of the token, normalized to the caption of the <code>type_id</code> value. This indicates whether the token is a Client Token, API Token, or one of the protocol-specific token types.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Type ID: The normalized token type identifier. Valid values: 0 (Unknown), 1 (Ticket Granting Ticket - Kerberos), 2 (Service Ticket - Kerberos), 3 (Identity Token - OIDC), 4 (Refresh Token - OIDC), 5 (SAML Assertion), 6 (Client Token - IdP-issued), 7 (API Token - generic API keys), 99 (Other).
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`

	// Unique ID: The unique ID of a token or key, if available, such as the <code>Secret ID</code> of Entra ID Application Registration Client Secrets.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// Network Zone: The network zone or geographic region that the token or key is authorized to be used from. This may represent network-based access restrictions, geographic limitations, or other zone-based authorization policies. Examples include Okta's network zone restrictions or cloud provider region restrictions.
	Zone *string `json:"zone,omitempty" parquet:"zone,optional"`
}

func (v *Token) Observable() (*int, string) {
	return nil, ""
}

var TokenFields = []arrow.Field{
	{Name: "created_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "expiration_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "is_renewable", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "modified_time", Type: arrow.FixedWidthTypes.Timestamp_ms, Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "tenant_uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "zone", Type: arrow.BinaryTypes.String, Nullable: true},
}

var TokenStruct = arrow.StructOf(TokenFields...)

var TokenSchema = arrow.NewSchema(TokenFields, nil)
var TokenClassname = "token"
